[project]
name = 'Tokenized-Smart-City-Waste-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collection-point-verification]
path = 'contracts/collection-point-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.fill-level-monitoring]
path = 'contracts/fill-level-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-analytics]
path = 'contracts/performance-analytics.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
